export const AXIOS_MEMBERS = "AXIOS_MEMBERS";
export const AXIOS_MEMBERS_REQUEST = "AXIOS_MEMBERS_REQUEST";
export const AXIOS_MEMBERS_SUCCESS = "AXIOS_MEMBERS_SUCCESS";
export const AXIOS_MEMBERS_FAILURE = "AXIOS_MEMBERS_FAILURE";
