export const AXIOS_PROJECTS = "AXIOS_PROJECTS";
export const AXIOS_PROJECTS_REQUEST = "AXIOS_PROJECTS_REQUEST";
export const AXIOS_PROJECTS_SUCCESS = "AXIOS_PROJECTS_SUCCESS";
export const AXIOS_PROJECTS_FAILURE = "AXIOS_PROJECTS_FAILURE";
