export const AXIOS_CONTENTS = "AXIOS_CONTENTS";
export const AXIOS_CONTENTS_REQUEST = "AXIOS_CONTENTS_REQUEST";
export const AXIOS_CONTENTS_SUCCESS = "AXIOS_CONTENTS_SUCCESS";
export const AXIOS_CONTENTS_FAILURE = "AXIOS_CONTENTS_FAILURE";
