export const AXIOS_PHOTOS = "AXIOS_PHOTOS";
export const AXIOS_PHOTOS_REQUEST = "AXIOS_PHOTOS_REQUEST";
export const AXIOS_PHOTOS_SUCCESS = "AXIOS_PHOTOS_SUCCESS";
export const AXIOS_PHOTOS_FAILURE = "AXIOS_PHOTOS_FAILURE";
